// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/converter/service/service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	PayedAt              *PayedAt  `protobuf:"bytes,1,opt,name=payedAt,proto3" json:"payedAt,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price                int32     `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Memo                 string    `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5e006af6adb896ad, []int{0}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetPayedAt() *PayedAt {
	if m != nil {
		return m.PayedAt
	}
	return nil
}

func (m *Item) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Item) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Item) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type PayedAt struct {
	Month                int32    `protobuf:"varint,1,opt,name=month,proto3" json:"month,omitempty"`
	Date                 int32    `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayedAt) Reset()         { *m = PayedAt{} }
func (m *PayedAt) String() string { return proto.CompactTextString(m) }
func (*PayedAt) ProtoMessage()    {}
func (*PayedAt) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5e006af6adb896ad, []int{1}
}
func (m *PayedAt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayedAt.Unmarshal(m, b)
}
func (m *PayedAt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayedAt.Marshal(b, m, deterministic)
}
func (dst *PayedAt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayedAt.Merge(dst, src)
}
func (m *PayedAt) XXX_Size() int {
	return xxx_messageInfo_PayedAt.Size(m)
}
func (m *PayedAt) XXX_DiscardUnknown() {
	xxx_messageInfo_PayedAt.DiscardUnknown(m)
}

var xxx_messageInfo_PayedAt proto.InternalMessageInfo

func (m *PayedAt) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *PayedAt) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

type Category struct {
	Big                  string   `protobuf:"bytes,1,opt,name=big,proto3" json:"big,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5e006af6adb896ad, []int{2}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetBig() string {
	if m != nil {
		return m.Big
	}
	return ""
}

func (m *Category) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5e006af6adb896ad, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*PayedAt)(nil), "PayedAt")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KakeiboClient is the client API for Kakeibo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KakeiboClient interface {
	AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error)
}

type kakeiboClient struct {
	cc *grpc.ClientConn
}

func NewKakeiboClient(cc *grpc.ClientConn) KakeiboClient {
	return &kakeiboClient{cc}
}

func (c *kakeiboClient) AddItem(ctx context.Context, in *Item, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Kakeibo/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KakeiboServer is the server API for Kakeibo service.
type KakeiboServer interface {
	AddItem(context.Context, *Item) (*Response, error)
}

func RegisterKakeiboServer(s *grpc.Server, srv KakeiboServer) {
	s.RegisterService(&_Kakeibo_serviceDesc, srv)
}

func _Kakeibo_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Item)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KakeiboServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kakeibo/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KakeiboServer).AddItem(ctx, req.(*Item))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kakeibo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Kakeibo",
	HandlerType: (*KakeiboServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _Kakeibo_AddItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/converter/service/service.proto",
}

func init() {
	proto.RegisterFile("backend/converter/service/service.proto", fileDescriptor_service_5e006af6adb896ad)
}

var fileDescriptor_service_5e006af6adb896ad = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xd1, 0x6a, 0xb3, 0x40,
	0x10, 0x85, 0x7f, 0x8d, 0xfe, 0xea, 0x14, 0x4a, 0x59, 0x7a, 0x21, 0x81, 0x82, 0x2c, 0x94, 0x7a,
	0x65, 0xc0, 0x3c, 0x41, 0xe8, 0x55, 0xe9, 0x4d, 0x99, 0x37, 0x58, 0x75, 0x48, 0xc5, 0xe8, 0xc8,
	0xba, 0x04, 0x42, 0x5f, 0xbe, 0xec, 0x18, 0x7b, 0x35, 0xe7, 0xec, 0xec, 0x37, 0x07, 0x0e, 0xbc,
	0x35, 0xa6, 0x1d, 0x68, 0xea, 0x0e, 0x2d, 0x4f, 0x57, 0xb2, 0x8e, 0xec, 0x61, 0x21, 0x7b, 0xed,
	0x5b, 0xda, 0x66, 0x35, 0x5b, 0x76, 0xac, 0x7f, 0x20, 0xfa, 0x70, 0x34, 0x2a, 0x0d, 0xc9, 0x6c,
	0x6e, 0xd4, 0x9d, 0x5c, 0x1e, 0x14, 0x41, 0xf9, 0x50, 0xa7, 0xd5, 0xd7, 0xea, 0x71, 0x5b, 0xa8,
	0x57, 0x48, 0x5b, 0xe3, 0xe8, 0xcc, 0xf6, 0x96, 0x87, 0xf2, 0x29, 0xab, 0xde, 0xef, 0x0f, 0xf8,
	0xb7, 0x52, 0xcf, 0x10, 0xcf, 0xb6, 0x6f, 0x29, 0xdf, 0x15, 0x41, 0x19, 0xe3, 0x6a, 0x94, 0x82,
	0x68, 0xa4, 0x91, 0xf3, 0xa8, 0x08, 0xca, 0x0c, 0x45, 0xeb, 0x23, 0x24, 0xf7, 0x10, 0x0f, 0x8d,
	0x3c, 0xb9, 0x6f, 0x49, 0x8f, 0x71, 0x35, 0x1e, 0xea, 0x8c, 0x23, 0x49, 0x8b, 0x51, 0xb4, 0xae,
	0x21, 0xdd, 0x42, 0xd5, 0x13, 0xec, 0x9a, 0xfe, 0x2c, 0x4c, 0x86, 0x5e, 0xfa, 0x3b, 0xcb, 0x68,
	0x2e, 0x17, 0x41, 0x32, 0x5c, 0x8d, 0xde, 0x43, 0x8a, 0xb4, 0xcc, 0x3c, 0x2d, 0xa4, 0x1e, 0x21,
	0xe4, 0x41, 0x90, 0x14, 0x43, 0x1e, 0xea, 0x12, 0x92, 0x4f, 0x33, 0x50, 0xdf, 0xb0, 0x7a, 0x81,
	0xe4, 0xd4, 0x75, 0xd2, 0x47, 0x5c, 0xf9, 0xb1, 0xcf, 0xaa, 0x8d, 0xd3, 0xff, 0x9a, 0xff, 0x52,
	0xd9, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x21, 0x00, 0x27, 0x5d, 0x01, 0x00, 0x00,
}
