// Code generated by protoc-gen-go. DO NOT EDIT.
// source: converter/service.proto

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ItemInput struct {
	PayedAt              *timestamp.Timestamp `protobuf:"bytes,1,opt,name=payedAt,proto3" json:"payedAt,omitempty"`
	Category             *Category            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Price                int32                `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Memo                 string               `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ItemInput) Reset()         { *m = ItemInput{} }
func (m *ItemInput) String() string { return proto.CompactTextString(m) }
func (*ItemInput) ProtoMessage()    {}
func (*ItemInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9df8cfe04334ab12, []int{0}
}
func (m *ItemInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemInput.Unmarshal(m, b)
}
func (m *ItemInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemInput.Marshal(b, m, deterministic)
}
func (dst *ItemInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemInput.Merge(dst, src)
}
func (m *ItemInput) XXX_Size() int {
	return xxx_messageInfo_ItemInput.Size(m)
}
func (m *ItemInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemInput.DiscardUnknown(m)
}

var xxx_messageInfo_ItemInput proto.InternalMessageInfo

func (m *ItemInput) GetPayedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PayedAt
	}
	return nil
}

func (m *ItemInput) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *ItemInput) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ItemInput) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type Category struct {
	Big                  string   `protobuf:"bytes,1,opt,name=big,proto3" json:"big,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9df8cfe04334ab12, []int{1}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetBig() string {
	if m != nil {
		return m.Big
	}
	return ""
}

func (m *Category) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_9df8cfe04334ab12, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*ItemInput)(nil), "ItemInput")
	proto.RegisterType((*Category)(nil), "Category")
	proto.RegisterType((*Response)(nil), "Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KakeiboClient is the client API for Kakeibo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KakeiboClient interface {
	AddItem(ctx context.Context, in *ItemInput, opts ...grpc.CallOption) (*Response, error)
}

type kakeiboClient struct {
	cc *grpc.ClientConn
}

func NewKakeiboClient(cc *grpc.ClientConn) KakeiboClient {
	return &kakeiboClient{cc}
}

func (c *kakeiboClient) AddItem(ctx context.Context, in *ItemInput, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/Kakeibo/AddItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KakeiboServer is the server API for Kakeibo service.
type KakeiboServer interface {
	AddItem(context.Context, *ItemInput) (*Response, error)
}

func RegisterKakeiboServer(s *grpc.Server, srv KakeiboServer) {
	s.RegisterService(&_Kakeibo_serviceDesc, srv)
}

func _Kakeibo_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KakeiboServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Kakeibo/AddItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KakeiboServer).AddItem(ctx, req.(*ItemInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kakeibo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Kakeibo",
	HandlerType: (*KakeiboServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _Kakeibo_AddItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "converter/service.proto",
}

func init() { proto.RegisterFile("converter/service.proto", fileDescriptor_service_9df8cfe04334ab12) }

var fileDescriptor_service_9df8cfe04334ab12 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x6a, 0xb4, 0x30,
	0x14, 0x86, 0x3f, 0x9d, 0x99, 0x4f, 0x73, 0x0a, 0xa5, 0x84, 0x42, 0xc5, 0x4d, 0x45, 0x28, 0xb8,
	0x69, 0x04, 0xdb, 0x1b, 0x18, 0xba, 0x1a, 0xba, 0x0b, 0xbd, 0x01, 0x7f, 0x4e, 0x45, 0x34, 0x9e,
	0x10, 0x33, 0x03, 0x73, 0x1b, 0xbd, 0xe2, 0x62, 0x6c, 0x66, 0x77, 0xde, 0xe4, 0x3c, 0x4f, 0xf2,
	0xc2, 0x53, 0x4b, 0xf3, 0x05, 0x8d, 0x45, 0x53, 0x2e, 0x68, 0x2e, 0x43, 0x8b, 0x42, 0x1b, 0xb2,
	0x94, 0x3e, 0xf7, 0x44, 0xfd, 0x84, 0xa5, 0x4b, 0xcd, 0xf9, 0xbb, 0xb4, 0x83, 0xc2, 0xc5, 0xd6,
	0x4a, 0x6f, 0x0b, 0xf9, 0x4f, 0x00, 0xec, 0x64, 0x51, 0x9d, 0x66, 0x7d, 0xb6, 0xfc, 0x1d, 0x22,
	0x5d, 0x5f, 0xb1, 0x3b, 0xda, 0x24, 0xc8, 0x82, 0xe2, 0xae, 0x4a, 0xc5, 0x26, 0x10, 0x5e, 0x20,
	0xbe, 0xbc, 0x40, 0xfa, 0x55, 0xfe, 0x02, 0x71, 0x5b, 0x5b, 0xec, 0xc9, 0x5c, 0x93, 0xd0, 0x61,
	0x4c, 0x7c, 0xfc, 0x1d, 0xc8, 0xdb, 0x15, 0x7f, 0x84, 0x83, 0x36, 0x43, 0x8b, 0xc9, 0x2e, 0x0b,
	0x8a, 0x83, 0xdc, 0x02, 0xe7, 0xb0, 0x57, 0xa8, 0x28, 0xd9, 0x67, 0x41, 0xc1, 0xa4, 0x9b, 0xf3,
	0x0a, 0x62, 0xcf, 0xf3, 0x07, 0xd8, 0x35, 0x43, 0xef, 0xbe, 0xc3, 0xe4, 0x3a, 0xae, 0x9e, 0x45,
	0xd5, 0xd3, 0xe4, 0xde, 0x62, 0x72, 0x0b, 0x79, 0x0a, 0xb1, 0xc4, 0x45, 0xd3, 0xbc, 0x20, 0xbf,
	0x87, 0x90, 0x46, 0x87, 0xc4, 0x32, 0xa4, 0xb1, 0x7a, 0x85, 0xe8, 0xb3, 0x1e, 0x71, 0x68, 0x88,
	0xe7, 0x10, 0x1d, 0xbb, 0x6e, 0x6d, 0xcc, 0x41, 0xdc, 0x8a, 0xa7, 0x4c, 0x78, 0x38, 0xff, 0xd7,
	0xfc, 0x77, 0x65, 0xdf, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xc1, 0x0f, 0xb2, 0x56, 0x01,
	0x00, 0x00,
}
